services:
  jenkins:
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8880:8080"
    restart: always

  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always